### PR TITLE
BTA-4825 Superset deployment

### PR DESCRIPTION
**Pull request by collins-b**
### SUMMARY
Prepare Superset deployment infrastructure

- Prepare necessary Terraform scripts
- Set up CI/CD on AWS
- Refactor
- Fixes
- etc

### CODE REVIEW

**Review by amirDaTa — APPROVED** [review]
All looks good.

**Review by amirDaTa — APPROVED** [review]
Approved

**Review by amirDaTa — APPROVED** [review]

**Review by gbrylinski — APPROVED** [review]
413 files is a bit scary (-;

**Comment by collins-b** [comment]
> 413 files is a bit scary (-;

hahaa. I know. Most of them aren't my changes. Are from superset:master branch

**Pull request merged**
